services:
  client:
    build: ./client
    ports:
      - 5173:80
    networks:
      - frontend
    depends_on:
      - api
  api:
    build: ./api
    ports: 
     - 9000:5000
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: postgres:16.9-bookworm
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
